# Generated by Django 5.0.7 on 2024-08-28 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city_lat', models.CharField(blank=True, max_length=200, null=True)),
                ('city_long', models.CharField(blank=True, max_length=200, null=True)),
                ('city_details', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('website', models.CharField(blank=True, max_length=300, null=True)),
                ('details', models.TextField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_description', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=500)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('storeys', models.CharField(max_length=200)),
                ('total_units', models.CharField(max_length=200)),
                ('price_starts', models.FloatField(blank=True, null=True)),
                ('price_end', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('project_address', models.CharField(max_length=400)),
                ('postal_code', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('occupancy', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Selling', 'Selling'), ('Planning Phase', 'Planning Phase'), ('Sold out', 'Sold out')], default='Selling', max_length=200)),
                ('project_type', models.CharField(choices=[('Condo', 'Condo'), ('Townhome', 'Townhome'), ('Semi-Detached', 'Semi-Detached'), ('Detached', 'Detached'), ('NaN', 'NaN')], default='Condo', max_length=200)),
                ('street_map', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='preconstruction_images/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preconstructions', to='preconstruction.city')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preconstructions', to='preconstruction.developer')),
            ],
        ),
        migrations.CreateModel(
            name='PreConstructionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='preconstruction_images/')),
                ('preconstruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='preconstruction.preconstruction')),
            ],
        ),
    ]
