# Generated by Django 5.0.7 on 2024-10-07 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0002_preconstruction_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preconstruction',
            name='floorplan',
            field=models.ImageField(blank=True, default='', null=True, upload_to='floorplans/'),
        ),
        migrations.CreateModel(
            name='PreConstructionFloorPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorplan', models.ImageField(blank=True, default='', null=True, upload_to='floorplans/')),
                ('PreConstruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floorplans', to='preconstruction.preconstruction')),
            ],
        ),
    ]
