# Generated by Django 5.0.7 on 2024-10-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0003_preconstruction_floorplan_preconstructionfloorplans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preconstructionfloorplans',
            old_name='PreConstruction',
            new_name='preConstruction',
        ),
    ]
