# Generated by Django 5.0.7 on 2024-10-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0004_rename_preconstruction_preconstructionfloorplans_preconstruction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preconstructionfloorplans',
            old_name='preConstruction',
            new_name='preconstruction',
        ),
    ]
