# Generated by Django 5.0.7 on 2024-10-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0006_blogpost_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, unique=True),
        ),
    ]
