# Generated by Django 5.0.7 on 2024-11-09 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0009_blogpost_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1BED', '1 Bedroom'), ('2BED', '2 Bedroom'), ('3BED', '3 Bedroom'), ('4BED', '4 Bedroom'), ('OTHER', 'Other')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='floorplans/')),
                ('name', models.CharField(max_length=100)),
                ('square_footage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('preconstruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan_images', to='preconstruction.preconstruction')),
            ],
            options={
                'ordering': ['category', 'created'],
            },
        ),
    ]
