# Generated by Django 5.0.7 on 2024-11-30 13:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0011_developer_commission_developer_email_developer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preconstruction',
            name='deposit_structure',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
