# Generated by Django 5.0.7 on 2024-11-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0012_preconstruction_deposit_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='preconstruction',
            name='project_completion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
