# Generated by Django 5.0.7 on 2024-12-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0013_preconstruction_project_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preconstruction',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Selling', 'Selling'), ('Planning Phase', 'Planning Phase'), ('Sold out', 'Sold out'), ('Move-in ready', 'Move-in ready')], default='Selling', max_length=200),
        ),
    ]
