# Generated by Django 5.0.7 on 2024-12-08 03:52

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0014_alter_preconstruction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='preconstruction',
            name='incentives',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
