# Generated by Django 5.0.7 on 2024-10-23 08:57

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacationprojects', '0002_blogcategory_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='vacationprojects.blogcategory'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='vacationprojects.city'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(help_text='Use the rich text editor to format your content', verbose_name='Blog Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='vacationprojects.country'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='A short summary of the blog post', max_length=500),
        ),
    ]
