# Generated by Django 5.2 on 2025-04-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacationprojects', '0003_alter_blogpost_categories_alter_blogpost_cities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='vacationprojects.tag'),
        ),
    ]
