# Generated by Django 5.0.7 on 2024-09-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('homeStaff', 'Home Staff'), ('Builder', 'Builder'), ('superuser', 'Superuser'), ('guest', 'Guest')], default='guest', max_length=10),
        ),
    ]
